source:       .
destination:  ./_site
plugins:      ./_plugins

lsi:          false
future:       false
pygments:     true
markdown:     rdiscount
permalink:    /:year/:month/:title.html
paginate:     5

author:
    name:       "Pablo Molina"
    givenName:  "Pablo"
    familyName: "Molina"
    alias:      "p2kmgcl"
    photo:      "http://dl.dropbox.com/u/6037255/perfil.jpg"
    mail:       "contact@pablomolina.me"
    url:        "http://pablomolina.me"
    bday:       "1991-10-01"
    links:
      - { name: "Google+",
          icon: "google-plus",
          url:  "http://googleplus.pablomolina.me" }
      - { name: "GitHub",
          icon: "github",
          url:  "http://github.pablomolina.me"     }
      - { name: "Twitter",
          icon: "twitter",
          url:  "http://twitter.pablomolina.me"    }
      - { name: "Facebook",
          icon: "facebook",
          url:  "http://facebook.pablomolina.me"   }
      - { name: "LinkedIn",
          icon: "linkedin",
          url:  "http://linkedin.pablomolina.me"   }
      - { name: "LastFM",
          icon: "music",
          url:  "http://lastfm.pablomolina.me"     }
      - { name: "DeviantArt",
          icon: "pencil",
          url:  "http://deviantart.pablomolina.me" }
      - { name: "YouTube",
          icon: "facetime-video",
          url:  "http://youtube.pablomolina.me"    }

web:
  url:          "http://pablomolina.me"
  title:        "Pablo Molina"
  subtitle:     "Piensa, inventa, comparte"

data:
  disqus:           "p2kmgcl"
  google-analytics: "UA-17072152-2"
  rss:              "http://feed.pablomolina.me"

meta:
  description:  "Blog personal de Pablo Molina sobre diseño web, programación, asuntos geek y, a veces, sencillamente cosas personales."
  keywords:
    - Diseño web
    - Programación
    - Tecnología
    - Internet
    - Web Design
    - Programation
    - Technology

quotes:
  - { quote: "Yo soy porque nosotros somos.",
      origin: "Ubuntu",
      link: "http://es.wikipedia.org/wiki/Ubuntu_(filosof%C3%ADa)" }
  - { quote: "Esta es mi historia y la acabaré cuando yo quiera.",
      origin: "Tidus - Final Fantasy X",
      link: "http://es.wikiquote.org/wiki/Final_Fantasy#Final_Fantasy_X" }

# Activa el uso de la librería less (javascript)
lesscss: false

# Módulos de la web (/script/modules)
jsmodules:
  - infinitescroll
  - cheatlist
  - randomquote
  - introwaypoint
  - showgotop
