source:       .
destination:  ./_site
plugins:      ./_plugins

lsi:          true
future:       false
pygments:     true
markdown:     maruku
permalink:    /:year/:month/:title.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

author:
    name:  "Pablo Molina"
    alias: "p2kmgcl"
    photo: "http://dl.dropbox.com/u/6037255/perfil.jpg"
    mail:  "p2kmgcl@gmail.com"
    links:
      googleplus:
        name: "Google+"
        icon: "google-plus"
      github:
        name: "GitHub"
      twitter:
        name: "Twitter"
      facebook:
        name: "Facebook"
      linkedin:
        name: "LinkedIn"
      lastfm:
        name: "LastFM"
        icon: "music"
      deviantart:
        name: "DeviantArt"
        icon: "pencil"
      youtube:
        name: "YouTube"
        icon: "facetime-video"

web:
  url:      "http://pablomolina.me"
  title:    "Pablo Molina"
  subtitle: "Piensa, inventa, comparte"
  disqus:   "p2kmgcl"
